---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: 10.0.0.194
    path: /mnt/backup/vault-warden # NFS path
  persistentVolumeReclaimPolicy: Retain


