# vaultwarden-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: ADMIN_TOKEN
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: DOMAIN
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
