---
- name: Create a VM from a template
  hosts:  pihole
  vars_files:
    - vars.yaml
  collections:
    - community.general
  tasks:
    - name: Clone a VM from an existing Ubuntu 22.04 template
      community.general.proxmox_kvm:
        #########################################
        #              credentials
        #########################################
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        #########################################
        #              the rest:
        #########################################
        # api_user: root@pam
        # api_password: secret
        # api_host: helldorado
        # name: spynal
        # node: sabrewulf
