---
- name: check if longhorn can be installed for k3s
  hosts: all
  become: yes
  tasks:
    - name: install jq
      ansible.builtin.apt:
        name: jq
        state: present

    - name: install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present

    - name: install nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: present


    - name: modprobes iscsi_tcp
      shell: modprobe iscsi_tcp
      become: true

    - name: enable iscsid
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: true

    - name: disable multipathd
      ansible.builtin.service:
        name: multipathd
        state: stopped
        enabled: no

    - name: Copy the local script to the remote host
      copy:
        src: ./env-longhorn-check.sh
        dest: /tmp/check.sh
        mode: '0755'
      become: true

    - name: Run the local script on the remote host
      shell: /tmp/check.sh
      become: true
      register: output
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k3smaster'] }}"
      run_once: true
      become: true

    - name: Display local script on the remote host
      debug: 
        var: output

