---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: default  # change if using another namespace
spec:
  type: ClusterIP  # this is default, you can omit it
  selector:
    app: uptime-kuma
  ports:
    - port: 3001        # port inside the cluster
      targetPort: 3001  # port in the pod
