---
apiVersion: v1
kind: Namespace
metadata:
  name: wallabag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: wallabag/wallabag:2.6.13
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_USER
              valueFrom: 
                secretKeyRef:
                  name: wallabag
                  key: POSTGRES_USER

            - name: DATABASE_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: wallabag
                  key: POSTGRES_PASSWORD

            - name: DATABASE_NAME
              valueFrom: 
                secretKeyRef:
                  name: wallabag
                  key: POSTGRES_DB

            - name: DATABASE_PORT 
              value: "5432"

            - name: DATABASE_HOST 
              value: wallabag-postgresql-svc

            - name: SYMFONY__ENV__APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: wallabag
                  key: APP_SECRET
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-postgresql
  namespace: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag-postgresql
  template:
    metadata:
      labels:
        app: wallabag-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:

        - name: POSTGRES_DB
          value: wallabag
        - name: POSTGRES_USER
          keyFrom: 
            secretKeyRef:
              name: wallabag
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          keyFrom: 
            secretKeyRef:
              name: wallabag
              key: POSTGRES_PASSWORD
        ports:
          - containerPort: 5432
          volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: wallabag-postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-postgresql-pvc
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wallabag-postgresql-svc
  namespace: wallabag
spec:
  selector:
    app: wallabag-postgresql
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30082
---
apiVersion: v1
kind: Service
metadata:
  name: wallabag-svc
  namespace: wallabag
spec:
  selector:
    app: wallabag
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
