---
- name: Install Longhorn on master node with k3s with kubectl
  hosts: k3master
  become: yes
  tasks:
    - name: Install Longhorn
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.7.1/deploy/longhorn.yaml
      register: output

    - name: Wait for Longhorn to be ready
      debug:
        var: output
