---
- name: Create VM From Proxmox Template
  hosts: localhost
  connection: local
  become: no                
  gather_facts: no

  vars:
    ansible_python_interpreter: /home/william/main-env/bin/python

  collections:
    - community.general

  vars_files:
    - vars.yaml

  tasks:
    - name: Create VM with Template with Cloud-Init
      community.general.proxmox_kvm:
        ######################################
        #            credentials             #
        ######################################
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ template_vmid }}"
        clone: "{{ template_name }}"
        name: "{{ new_vm_name }}"
        newid: "{{ new_vm_id }}"
        format: qcow2
        ipconfig:
          ipconfig0: "ip={{ new_vm_ip }}/24,gw={{ new_vm_gateway }}"
        full: true
        sshkeys: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"
        state: present
        cores: "{{ new_vm_cores }}"
        memory: "{{ new_vm_memory }}"
        storage: "{{ vm_storage  }}"
        agent: 1
        timeout: 1200
      register: new_vm

    - name: Prints the VM creation details
      debug:
        var: new_vm

    - name: Start the new VM
      community.general.proxmox_kvm:
        ######################################
        #            credentials             #
        ######################################
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vm_id }}"
        state: started
        timeout: 1200
      register: start_status

    - name: Prints the start of the vm status
      debug:
        var: start_status
