- vars:
  local_ssh_pub_key: " {{ lookup('file', '/home/william/.ssh/id_rsa.pub') }}"

- name: Load local SSH key
  set_fact:
    pubkey: "{{ lookup('file', local_ssh_pub_key) }}"
  delegate_to: localhost

- name: Copy the SSH key to the VM
  copy:
    content: "{{ pubkey }}"
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: true
