- name: Load local SSH key
  set_fact:
    pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Copy the SSH key to the VM
  copy:
    content: "{{ pubkey }}"
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: true
