- name: Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: restart sshd
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Wait for SSH to come back
  ansible.builtin.wait_for_connection:
    delay: 3          
    timeout: 60       
