---
- name: Create VM From Proxmox Template
  hosts: test_vm
  become: true
  gather_facts: no
  # vars_files:
  #   - vars.yaml
  tasks:
    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: restart sshd
      service:
        name: sshd
        state: restarted
