---
- name: Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: Validate SSH config
  ansible.builtin.command: sshd -t
  become: true

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
  become: true
