---
name: Prevent root login
#SPDX-License-Identifier: MIT-0
---
- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: restart sshd
  service:
    name: sshd
    state: restarted
