services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.9
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images/:/app/images
      - ./icons:/app/icons
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York 
      - HOMEPAGE_VAR_TAILSCALE_API_KEY=$HOMEPAGE_VAR_TAILSCALE_API_KEY      # env var should start with HOMEPAGE_VAR
      - HOMEPAGE_VAR_TAILSCALE_DEVICE_ID_1=$HOMEPAGE_VAR_TAILSCALE_DEVICE_ID_1
      - HOMEPAGE_VAR_TAILSCALE_DEVICE_ID_2=$HOMEPAGE_VAR_TAILSCALE_DEVICE_ID_2
      - HOMEPAGE_VAR_MINIFLUX_API_KEY=$HOMEPAGE_VAR_MINIFLUX_API_KEY
    restart: unless-stopped
