---
- name: checks for disk usage of different servers and sends alert to Discord
  hosts: prod_servers
  become: true
  tasks:
    - name: Check disk usage percentage on /
      ansible.builtin.shell: |
          df -h / | awk 'NR==2 {print $5}' | tr -d '%'
      register: disk_usage
      changed_when: false

    - name: Notify gotify if disk usage is above 80%
      ansible.builtin.uri:
        url: "{{ gotify_webhook_url }}"
        method: POST
        headers:
           Content-Type: "application/json; charset=utf-8"
        body: "{{ {'message': 'Disk usage alert on ' ~ inventory_hostname ~ ': ' ~ disk_usage.stdout ~ '%'} | to_json }}"
        status_code: 200
      # when:
      #    - disk_usage.stdout is defined
      #    - disk_usage.stdout | int > 80
