---
- name: trigger proxmox vzdump via cli
  hosts: proxmox_prod_1
  gather_facts: no
  become: yes
  vars:
    backup_vms:
      - 103
      - 105
      - 107
      - 109
  tasks:
    - name: run vzdump backup on each vm
      ansible.builtin.command: >
        vzdump {{ item }} 
        --storage vm-backup
        --mode snapshot 
        --compress zstd
        --prune-backups keep-last=3
      loop: "{{ backup_vms }}"
