apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: miniflux   # <--- add this line
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
