---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-postgresql
  namespace: miniflux
type: Opaque
stringData:
  postgres-password: changeme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-postgresql
  namespace: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux-postgresql
  template:
    metadata:
      labels:
        app: miniflux-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: miniflux
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: changeme
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-postgresql
  namespace: miniflux
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: miniflux-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: ghcr.io/miniflux/miniflux:2.2.5
        ports:
        - containerPort: 8080
        env:
        - name: ADMIN_USERNAME
          value: admin
        - name: ADMIN_PASSWORD
          value: adminpass  # Change this
        - name: CREATE_ADMIN
          value: "1"
        - name: RUN_MIGRATIONS
          value: "1"
        - name: DATABASE_URL
          value: postgres://postgres:changeme@miniflux-postgresql/miniflux?sslmode=disable
        volumeMounts:
        - name: nfs
          mountPath: /var/lib/miniflux  # Optional
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs  # Optional PVC
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
spec:
  selector:
    app: miniflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
