---
- name: Create VM From Proxmox ISO
  hosts: proxmox
  connection: local
  #become: yes
  vars:
    ansible_python_interpreter: /home/william/main-env/bin/python3
  collections:
    - community.general
  vars_files:
    - vars.yaml
  tasks:
    - name: Create VM with ISO
      community.general.proxmox_kvm:
        # credentials
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"

        vmid: "{{ new_vm_id }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"

        memory: 2048
        cores: 2

        ide:
          ide2: "local:iso/{{ iso_name }},media=cdrom"
        sata:
          sata0: "local-lvm:30"
        net:
          net0: "virtio,bridge=vmbr0"

        ostype: l26
        boot: "cdn"
        bootdisk: sata0

        state: present
