proxmox_api_token_id: "root@pam!my-token"
proxmox_api_user: "root@pam"
proxmox_node: "pve"
proxmox_pass: "rodent45"
proxmox_api_host: "10.0.0.225"

iso_url:  https://releases.ubuntu.com/22.04/ubuntu-22.04.4-live-server-amd64.iso
iso_name:  openmediavault.iso
iso_dest: /var/lib/vz/template/iso/ubuntu-22.04.4.iso
iso_dir:  /var/lib/vz/template/iso/
local_omv: /home/william/Downloads/openmediavault_7.4.17-amd64.iso

new_vm_id: 106
vm_name: home-VM-srv-4


























