---
#  YOU SHOULD EDIT THIS FILE FIRST on /etc/pihole/pihole.toml:
# Put configuration into read-only mode. This will prevent any changes to the
# configuration file via the API or CLI. This setting useful when a configuration is
# to be forced/modified by some third-party application (like infrastructure-as-code
# providers) and should not be changed by any means.
# readOnly = true

- name: add an IP to local dns in pihole
  hosts: pihole
  become: yes
  vars_files:
    - vars.yaml
  tasks:
  - name: Insert host block into Pi-hole TOML
    ansible.builtin.lineinfile:
      path: /etc/pihole/pihole.toml
      firstmatch: yes
      state: present
      insertafter: '^\s*hosts\s*=\s*\['
      line:  '   "{{ new_ip }} {{ new_domain }}",'

  - name: Restart Pi-hole DNS
    ansible.builtin.command: pihole reloaddns
