---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc # New PVC for PostgreSQL data
  namespace: miniflux
spec:
  accessModes:
    - ReadWriteOnce # Standard for single-node local storage
  resources:
    requests:
      storage: 5Gi # Adjust storage size as needed for PostgreSQL
  storageClassName: local-path # Use the K3s default local provisioner
