---
- name: Installing Gitea
  hosts: pi_servers
  become: true
  gather_facts: no
  tasks:
    - name: Create git user
      ansible.builtin.user:
        name: git
        shell: /bin/bash
        comment: "Git Version Control"
        create_home: true
        system: true
        password_lock: true

    - name: Ensure Gitea data directories exist
      ansible.builtin.file:
        path: "/var/lib/gitea/{{ item }}"
        state: directory
        owner: git
        group: git
        mode: '0750'
      loop:
        - custom
        - data
        - log

    - name: Ensure /etc/gitea directory exists
      ansible.builtin.file:
        path: /etc/gitea
        state: directory
        owner: root
        group: git
        mode: '0770'

    - name: Download Gitea binary
      ansible.builtin.get_url:
        url: https://dl.gitea.com/gitea/1.24.2/gitea-1.24.2-linux-arm64
        dest: /usr/local/bin/gitea
        mode: '0755'
        force: false

    - name: Set owner and group on Gitea binary
      ansible.builtin.file:
        path: /usr/local/bin/gitea
        owner: root
        group: root

    - name: Copy gitea.service to systemd
      ansible.builtin.copy:
        src: ./gitea.service
        dest: /etc/systemd/system/gitea.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start Gitea service
      ansible.builtin.systemd_service:
        name: gitea
        enabled: true
        state: started
        daemon_reload: true

