---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.home.interlink`)
      kind: Rule
      services:
        - name: authentik
          port: 80
  tls:
    secretName: authentik-tls
