---
- name: create directory
  file:
    path: "{{ vaultwarden_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: copy files to the directory 
  copy:
    src: "{{ item }}"
    dest: "{{ vaultwarden_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop: "{{ vaultwarden_files }}"

- name: Apply Kubernetes manifests
  command: kubectl apply -f {{ vaultwarden_path }}/{{ item }}
  loop: "{{ vaultwarden_files }}"
