---
- name: Clonse a VM from an existing Ubuntu 22.04 template. 
  connection: local
  hosts: all
  vars_files:
    - vars.yaml
  vars:
    ansible_python_interpreter: /home/william/main-env/bin/python3
  collections:
    - community.general
  tasks:
    - name: Clone a VM from an existing Ubuntu 22.04 template
      community.general.proxmox_kvm:
        #########################################
        #              credentials
        #########################################
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"

        clone: "ubuntu-22.04-template" # VM template
        name:  "home-Cluster-srv-3"
        vmid: 1001
        newid: 1002                    # New VM ID

        ide:
          ide2: "local:cloudinit,format=qcow2"
        ciuser: "{{ ci_user }}"
        cipassword: "{{ ci_password }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        sshkeys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

        net:
          net0: virtio,bridge=vmbr0

        full: true                     # Full clone, not linked
        timeout: 600
        state: present
