apiVersion: v1
kind: Service
metadata:
  name: npm
  namespace: npm
spec:
  type: LoadBalancer
  selector:
    app: npm
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
    - port: 81
      targetPort: 81
      name: admin

