---
- name: Create VM From Proxmox Template
  hosts: proxmox
  connection: local
  #become: yes
  vars:
    ansible_python_interpreter: /home/william/main-env/bin/python3
  collections:
    - community.general
  vars_files:
    - vars.yaml
  tasks:
    - name: Create VM with Template with Cloud-Init
      community.general.proxmox_kvm:
        # credentials
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"

        vmid: "{{ new_vm_id }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"

        ipconfig:
          ipconfig0: 'ip={{ new_vm_ip }}/24,gw={{ new_vm_gateway }}'

        ide:
          ide2: "local:iso/{{ iso_name }},media=cdrom"
        sata:
          sata0: "local-lvm:30"
        net:
          net0: "virtio,bridge=vmbr0"
        timeout: 600

    - name: Start the new VM
      community.general.proxmox_kvm:
        # credentials
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ new_vm_id }}"
        state: started
      timeout: 600
