---
- name:  Install an deploy GrayLog
  hosts: "{{ new_vm_ip }}"
  become: yes
  collections:
    - community.general
  vars_files:
    - vars.yaml
  tasks:

    - name: Open firewall ports with UFW
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 9000
        - 9200
        - 27017
        - 9300
        - 5044

    - name: Install GrayLog
      pkg:
      - curl
      - gnupg

    - name: Download MongoDB GPG key
      get_url:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        dest: /tmp/mongodb-server-7.0.asc
        mode: '0644'

    - name: Convert MongoDB GPG key to GPG format
      command: >
        gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg /tmp/mongodb-server-7.0.asc
      become: true

    - name: Add MongoDB 7.0 APT repository
      apt_repository:
        repo: 'deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse'
        filename: 'mongodb-org-7.0'
        state: present
      become: true

    - name: update cache
      apt:
        update_cache: true
      become: true

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Get Graylog deb package
      get_url:
        url: https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}.deb
        dest: /tmp/graylog.deb
        mode: '0644'

    - name: Install Graylog
      ansible.builtin.apt:
        name: /tmp/graylog.deb
        state: present

    - name: Start Graylog
      service:
        name: graylog
        state: started

    - name: update cache
      apt:
        update_cache: true
      become: true

    - name: ensure linux vm.max_map_count is set to 262144
      sysctl:
        name: "vm.max_map_count"
        value: "262144"
        state: present
      become: true

    - name: generate random password
      ansible.builtin.command:  openssl rand -hex 32
      become: true

    - name: ensure linux vm.swappiness is set to 1
      ansible.builtin.command:  sysctl --system
      become: true

    - name: Set password_secret in datanode.conf
      lineinfile:
        path: /etc/graylog/datanode/datanode.conf
        regexp: '^password_secret\s*='
        line: 'password_secret = {{ graylog_password_secret }}'
        create: yes

    - name: Set opensearch_heap in datanode.conf
      lineinfile:
        path: /etc/graylog/datanode/datanode.conf
        regexp: '^opensearch_heap\s*='
        line: 'opensearch_heap = 8g'
        create: yes
