repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    set:
      - name: service.type
        value: NodePort

      - name: admin.existingSecret
        value: grafana-admin-secret

      - name: admin.passwordKey
        value: admin-password

  - name: loki
    namespace: monitoring
    chart: grafana/loki-stack
    set:
      - name: promtail.enabled
        value: true
      - name: grafana.enabled
        value: false
