---
- name: Configure NFS server
  hosts: nfs_server
  become: true
  gather_facts: no
  collections:
    - community.general
  vars_files:
    - vars.yaml
  tasks:
    - name: Install nfs-kernel-server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
      retries: 5
      delay: 10
      register: apt_result
      until: apt_result is success

    - name: Enable and start NFS server
      systemd:
        name: nfs-server
        enabled: true
        state: started
      become: true

    - name: Create shared directory
      file:
        path: "{{ shared_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: '0755'

    - name: Configure /etc/exports
      copy:
        dest: /etc/exports
        content: |
          {{ shared_dir }} {{ allowed_hosts }}(rw,sync,no_subtree_check,no_root_squash)

    - name: Export the shares
      command: exportfs -ra


