apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden # Or your preferred namespace
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest # Or a specific version, e.g., 1.29.0
        ports:
        - containerPort: 80 # HTTP port for Vaultwarden
        - containerPort: 3012 # WebSocket port for Vaultwarden
        env:
        - name: DOMAIN
          value: "https://vw.home.interlink" # IMPORTANT: Update this with your actual IP or local FQDN
        - name: ROCKET_PORT
          value: "80" # Vaultwarden listens on port 80 internally
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: WEBSOCKET_ENABLED
          value: "true"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secret
              key: ADMIN_TOKEN
        volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
      volumes:
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc # Will create this next
